In [1]:
from acquire import *
import numpy as np

In [2]:
robot_dict = read_pickles_in_directory("pickle-files")

In [3]:
final_df = create_long_format_stats_df(robot_dict)

In [4]:
final_df[final_df['RobotName'] == 'tombstone-2']

        RobotName                  Stats      Year Value
1690  tombstone-2          Total matches    Career    11
1691  tombstone-2         Win percentage    Career   91%
1692  tombstone-2             Total wins    Career    10
1693  tombstone-2                 Losses    Career     1
1694  tombstone-2              Knockouts    Career     8
1695  tombstone-2          KO percentage    Career   73%
1696  tombstone-2  Average knockout time    Career  66 s
1697  tombstone-2      Knockouts against    Career     0
1698  tombstone-2  KO against percentage    Career    0%
1699  tombstone-2   Judges decision wins    Career     2
1700  tombstone-2          Total matches  Season 2     6
1701  tombstone-2         Win percentage  Season 2  100%
1702  tombstone-2             Total wins  Season 2     6
1703  tombstone-2                 Losses  Season 2     0
1704  tombstone-2              Knockouts  Season 2     4
1705  tombstone-2          KO percentage  Season 2   67%
1706  tombstone-2  Average knockout time  Season 2  55 s
1707  tombstone-2      Knockouts against  Season 2     0
1708  tombstone-2  KO against percentage  Season 2    0%
1709  tombstone-2   Judges decision wins  Season 2     2
1710  tombstone-2          Total matches  Season 1     5
1711  tombstone-2         Win percentage  Season 1   80%
1712  tombstone-2             Total wins  Season 1     4
1713  tombstone-2                 Losses  Season 1     1
1714  tombstone-2              Knockouts  Season 1     4
1715  tombstone-2          KO percentage  Season 1   80%
1716  tombstone-2  Average knockout time  Season 1  78 s
1717  tombstone-2      Knockouts against  Season 1     0
1718  tombstone-2  KO against percentage  Season 1    0%
1719  tombstone-2   Judges decision wins  Season 1     0

In [5]:
final_df[(final_df['RobotName'] == 'riptide-wcvii') & (final_df['Year'] == "Career")]

           RobotName                  Stats    Year Value
13630  riptide-wcvii          Total matches  Career    11
13631  riptide-wcvii         Win percentage  Career   82%
13632  riptide-wcvii             Total wins  Career     9
13633  riptide-wcvii                 Losses  Career     2
13634  riptide-wcvii              Knockouts  Career     8
13635  riptide-wcvii          KO percentage  Career   73%
13636  riptide-wcvii  Average knockout time  Career  71 s
13637  riptide-wcvii      Knockouts against  Career     1
13638  riptide-wcvii  KO against percentage  Career    9%
13639  riptide-wcvii   Judges decision wins  Career     0

# Actions

In [6]:
final_df['Stats'] = final_df['Stats'].replace('Average knockout time', 'Average Knockout Time Seconds')

In [7]:
final_df['Value'].fillna(0, inplace=True)

In [8]:
final_df['Value'] = final_df['Value'].apply(lambda x: float(x.replace('s', '').replace('%', '')) if isinstance(x, str) else x)

In [9]:
final_df = final_df.reset_index(drop=True)

# Verify

In [10]:
final_df[final_df['RobotName'] == 'tombstone-2']

        RobotName                          Stats      Year  Value
1690  tombstone-2                  Total matches    Career   11.0
1691  tombstone-2                 Win percentage    Career   91.0
1692  tombstone-2                     Total wins    Career   10.0
1693  tombstone-2                         Losses    Career    1.0
1694  tombstone-2                      Knockouts    Career    8.0
1695  tombstone-2                  KO percentage    Career   73.0
1696  tombstone-2  Average Knockout Time Seconds    Career   66.0
1697  tombstone-2              Knockouts against    Career    0.0
1698  tombstone-2          KO against percentage    Career    0.0
1699  tombstone-2           Judges decision wins    Career    2.0
1700  tombstone-2                  Total matches  Season 2    6.0
1701  tombstone-2                 Win percentage  Season 2  100.0
1702  tombstone-2                     Total wins  Season 2    6.0
1703  tombstone-2                         Losses  Season 2    0.0
1704  tombstone-2                      Knockouts  Season 2    4.0
1705  tombstone-2                  KO percentage  Season 2   67.0
1706  tombstone-2  Average Knockout Time Seconds  Season 2   55.0
1707  tombstone-2              Knockouts against  Season 2    0.0
1708  tombstone-2          KO against percentage  Season 2    0.0
1709  tombstone-2           Judges decision wins  Season 2    2.0
1710  tombstone-2                  Total matches  Season 1    5.0
1711  tombstone-2                 Win percentage  Season 1   80.0
1712  tombstone-2                     Total wins  Season 1    4.0
1713  tombstone-2                         Losses  Season 1    1.0
1714  tombstone-2                      Knockouts  Season 1    4.0
1715  tombstone-2                  KO percentage  Season 1   80.0
1716  tombstone-2  Average Knockout Time Seconds  Season 1   78.0
1717  tombstone-2              Knockouts against  Season 1    0.0
1718  tombstone-2          KO against percentage  Season 1    0.0
1719  tombstone-2           Judges decision wins  Season 1    0.0

# Match History Next!

In [11]:
robot_dict['tombstone-2021']['match_history']

,Season,Round,Matchup,Results
0,2021,Episode 601,Captain Shrederator vs Tombstone,Captain Shrederator by KO 2m2s
1,2021,Episode 604,Tombstone vs Mammoth,Tombstone by JD
2,2021,Episode 608,Free Shipping vs Tombstone,Tombstone by JD
3,2021,Episode 612,Jackpot vs Tombstone,Jackpot by KO 40s
4,2021,SCSF 6,Tombstone vs Tantrum,Tantrum by KO 1m25s
5,2020,Bounty Tombstone,Tombstone vs Gruff,Tombstone by KO 2m11s
6,2020,Episode 501,Tombstone vs End Game,End Game by KO 39s
7,2020,Episode 504,Slap Box vs Tombstone,Tombstone by KO 1m19s
8,2020,Episode 508,Tombstone vs Skorpios,Skorpios by KO 1m58s
9,2020,Episode 511,MaDCaTter vs Tombstone,Tombstone by KO 2m8s
10,2020,Episode 513,Black Dragon vs Tombstone,Black Dragon by JD
11,2019,Episode 1,Tombstone vs Lock-Jaw,Tombstone by KO 48s
12,2019,Episode 11,Tombstone vs Gruff,Tombstone by JD
13,2019,Episode 15,Tombstone vs Quantum,Tombstone by KO 32s
14,2019,Episode 16,Tombstone vs Bite Force,Bite Force by KO 52s
15,2019,Episode 16,Tombstone vs Whiplash,Tombstone by KO 1m40s
16,2019,Episode 4,Tombstone vs SawBlaze,Tombstone by KO 1m42s
17,2019,Episode 7,Tombstone vs Rotator,Rotator by KO 2m59s
18,2018,Day 1 Session 1,Tombstone vs Minotaur,Tombstone by KO 2m22s
19,2018,Day 10 Session 2,Tombstone vs Tantrum,Tombstone by KO 1m17s
20,2018,Day 2 Session 2,Gigabyte vs Tombstone,Tombstone by KO 1m9s
21,2018,Day 6 Session 2,Tombstone vs Whiplash,Tombstone by KO 1m14s
22,2018,Day 7 Session 2,Tombstone vs DUCK!,Tombstone by KO 2m37s
23,2018,Sweet 16 2018,Tombstone vs Bombshell,Bombshell by KO 1m57s
24,2016,Final,Tombstone vs Bombshell,Tombstone by KO 53s
25,2016,Qualifiers Session 2,Tombstone vs Black Ice,Tombstone by KO 1m1s
26,2016,Quarter Finals,Tombstone vs Beta,Tombstone by JD
27,2016,Round of 32,Tombstone vs Escape Velocity,Tombstone by KO 45s
28,2016,Semi Finals,Tombstone vs Yeti,Tombstone by JD
29,2016,Sweet 16,Tombstone vs Brutus,Tombstone by KO 59s

In [12]:
# Create an empty list to store the formatted match history dataframes
match_history_dfs = []

# Loop through each robot in the robot_dict dictionary
for robot_name, tables_dict in robot_dict.items():
    # Check if the 'match_history' key exists in the tables_dict
    if 'match_history' in tables_dict:
        # Extract the match_history dataframe for this robot
        match_history_df = tables_dict['match_history']
        # Add a RobotName column with the robot's name
        match_history_df['RobotName'] = robot_name
        # Rename the columns in match_history_df
        match_history_df.columns = [col + '_match_history' if col not in ['Season', 'RobotName'] else col for col in match_history_df.columns]
        
        # Append the formatted dataframe to the list
        match_history_dfs.append(match_history_df)
        
# Concatenate all the formatted match history dataframes into a single dataframe
all_match_history_df = pd.concat(match_history_dfs)

# Remove double "_matchup_history" suffix
all_match_history_df.columns = all_match_history_df.columns.str.replace('_match_history_match_history', '_match_history')

# Melt the all_match_history_df table
all_match_history_df_melt = pd.melt(
    all_match_history_df,
    id_vars=['Season', 'RobotName'],
    value_vars=['Round_match_history', 'Matchup_match_history', 'Results_match_history', 'Opponent_match_history'],
    var_name='Stats',
    value_name='Value'
)
all_match_history_df_melt = all_match_history_df_melt.rename(columns={'Season': 'Year'})

# Verify New Dataframe!

In [14]:
all_match_history_df.head()

,Season,Round_match_history,Matchup_match_history,Results_match_history,RobotName,Opponent_match_history
0,2021,Episode 601,Captain Shrederator vs Tombstone,Captain Shrederator by KO 2m2s,tombstone-2021,NaN
1,2021,Episode 604,Tombstone vs Mammoth,Tombstone by JD,tombstone-2021,NaN
2,2021,Episode 608,Free Shipping vs Tombstone,Tombstone by JD,tombstone-2021,NaN
3,2021,Episode 612,Jackpot vs Tombstone,Jackpot by KO 40s,tombstone-2021,NaN
4,2021,SCSF 6,Tombstone vs Tantrum,Tantrum by KO 1m25s,tombstone-2021,NaN

### Stupid double Suffix

In [15]:
all_match_history_df.columns = all_match_history_df.columns.str.replace('_match_history_match_history', '_match_history')

In [16]:
all_match_history_df

,Season,Round_match_history,Matchup_match_history,Results_match_history,RobotName,Opponent_match_history
0,2021,Episode 601,Captain Shrederator vs Tombstone,Captain Shrederator by KO 2m2s,tombstone-2021,NaN
1,2021,Episode 604,Tombstone vs Mammoth,Tombstone by JD,tombstone-2021,NaN
2,2021,Episode 608,Free Shipping vs Tombstone,Tombstone by JD,tombstone-2021,NaN
3,2021,Episode 612,Jackpot vs Tombstone,Jackpot by KO 40s,tombstone-2021,NaN
4,2021,SCSF 6,Tombstone vs Tantrum,Tantrum by KO 1m25s,tombstone-2021,NaN
...,...,...,...,...,...,...
7,2021,Episode 611,Shatter vs Riptide,Riptide by KO 1m9s,riptide-wcvii,NaN
8,2021,Episode 613,Upper Cut vs Riptide,Riptide by KO 1m9s,riptide-wcvii,NaN
9,2021,Episode 614,Riptide vs SawBlaze,SawBlaze by KO 1m38s,riptide-wcvii,NaN
10,2021,Not Aired,Bloodsport vs Riptide,Riptide by JD,riptide-wcvii,NaN
11,2021,Not Aired,Riptide vs Jackpot,Riptide by KO 55s,riptide-wcvii,NaN

### Robots With Old Naming Style in Matchup History Table for Opponent Column

In [18]:
all_match_history_df[~all_match_history_df['Opponent_match_history'].isnull()].head()

,Season,Round_match_history,Matchup_match_history,Results_match_history,RobotName,Opponent_match_history
0,Season 2,Qualifier,NaN,Lost by KO (0:44),nightmare-2,Stinger
1,Season 2,Round of 32,NaN,Won by KO (0:48),nightmare-2,Icewave
2,Season 2,Round of 16,NaN,Lost by KO (3:00),nightmare-2,Beta
3,Season 1,Qualifier,NaN,Lost by KO (2:06),nightmare-2,Warrior Clan
0,Season 2,Qualifier,NaN,Lost by KO (0:44),nightmare,Stinger

### New Naming Style in Matchup History Table Columns for Opponents

In [20]:
all_match_history_df[['Matchup_match_history']]

               Matchup_match_history
0   Captain Shrederator vs Tombstone
1               Tombstone vs Mammoth
2         Free Shipping vs Tombstone
3               Jackpot vs Tombstone
4               Tombstone vs Tantrum
..                               ...
7                 Shatter vs Riptide
8               Upper Cut vs Riptide
9                Riptide vs SawBlaze
10             Bloodsport vs Riptide
11                Riptide vs Jackpot

[4740 rows x 1 columns]

In [21]:
all_match_history_df.shape

(4740, 6)

In [22]:
all_match_history_df

,Season,Round_match_history,Matchup_match_history,Results_match_history,RobotName,Opponent_match_history
0,2021,Episode 601,Captain Shrederator vs Tombstone,Captain Shrederator by KO 2m2s,tombstone-2021,NaN
1,2021,Episode 604,Tombstone vs Mammoth,Tombstone by JD,tombstone-2021,NaN
2,2021,Episode 608,Free Shipping vs Tombstone,Tombstone by JD,tombstone-2021,NaN
3,2021,Episode 612,Jackpot vs Tombstone,Jackpot by KO 40s,tombstone-2021,NaN
4,2021,SCSF 6,Tombstone vs Tantrum,Tantrum by KO 1m25s,tombstone-2021,NaN
...,...,...,...,...,...,...
7,2021,Episode 611,Shatter vs Riptide,Riptide by KO 1m9s,riptide-wcvii,NaN
8,2021,Episode 613,Upper Cut vs Riptide,Riptide by KO 1m9s,riptide-wcvii,NaN
9,2021,Episode 614,Riptide vs SawBlaze,SawBlaze by KO 1m38s,riptide-wcvii,NaN
10,2021,Not Aired,Bloodsport vs Riptide,Riptide by JD,riptide-wcvii,NaN
11,2021,Not Aired,Riptide vs Jackpot,Riptide by KO 55s,riptide-wcvii,NaN

# Melt Matchup

#### Stats Layout

In [24]:
final_df.head()

        RobotName           Stats    Year  Value
0  tombstone-2021   Total matches  Career   35.0
1  tombstone-2021  Win percentage  Career   71.0
2  tombstone-2021      Total wins  Career   25.0
3  tombstone-2021          Losses  Career   10.0
4  tombstone-2021       Knockouts  Career   20.0

#### Matchup History Layout: Before

In [25]:
all_match_history_df.head()

,Season,Round_match_history,Matchup_match_history,Results_match_history,RobotName,Opponent_match_history
0,2021,Episode 601,Captain Shrederator vs Tombstone,Captain Shrederator by KO 2m2s,tombstone-2021,NaN
1,2021,Episode 604,Tombstone vs Mammoth,Tombstone by JD,tombstone-2021,NaN
2,2021,Episode 608,Free Shipping vs Tombstone,Tombstone by JD,tombstone-2021,NaN
3,2021,Episode 612,Jackpot vs Tombstone,Jackpot by KO 40s,tombstone-2021,NaN
4,2021,SCSF 6,Tombstone vs Tantrum,Tantrum by KO 1m25s,tombstone-2021,NaN

#### Melt

In [27]:
# Melt the all_match_history_df table
all_match_history_df_melt = pd.melt(
    all_match_history_df,
    id_vars=['Season', 'RobotName'],
    value_vars=['Round_match_history', 'Matchup_match_history', 'Results_match_history', 'Opponent_match_history'],
    var_name='Stats',
    value_name='Value'
)
all_match_history_df_melt = all_match_history_df_melt.rename(columns={'Season': 'Year'})

#### Matchup History Layout: After

In [42]:
all_match_history_df_melt.head()

   Year       RobotName                Stats        Value
0  2021  tombstone-2021  Round_match_history  Episode 601
1  2021  tombstone-2021  Round_match_history  Episode 604
2  2021  tombstone-2021  Round_match_history  Episode 608
3  2021  tombstone-2021  Round_match_history  Episode 612
4  2021  tombstone-2021  Round_match_history       SCSF 6

# Matchup + Stats Had a Baby!

#### Stats

In [43]:
final_df.head()

        RobotName           Stats    Year  Value
0  tombstone-2021   Total matches  Career   35.0
1  tombstone-2021  Win percentage  Career   71.0
2  tombstone-2021      Total wins  Career   25.0
3  tombstone-2021          Losses  Career   10.0
4  tombstone-2021       Knockouts  Career   20.0

#### Matchup History

In [44]:
all_match_history_df_melt.head()

   Year       RobotName                Stats        Value
0  2021  tombstone-2021  Round_match_history  Episode 601
1  2021  tombstone-2021  Round_match_history  Episode 604
2  2021  tombstone-2021  Round_match_history  Episode 608
3  2021  tombstone-2021  Round_match_history  Episode 612
4  2021  tombstone-2021  Round_match_history       SCSF 6

In [46]:
joined_df = final_df.merge(all_match_history_df_melt, on=['RobotName', 'Year'], how='left')

In [47]:
joined_df

,RobotName,Stats_x,Year,Value_x,Stats_y,Value_y
0,tombstone-2021,Total matches,Career,35.0,NaN,NaN
1,tombstone-2021,Win percentage,Career,71.0,NaN,NaN
2,tombstone-2021,Total wins,Career,25.0,NaN,NaN
3,tombstone-2021,Losses,Career,10.0,NaN,NaN
4,tombstone-2021,Knockouts,Career,20.0,NaN,NaN
...,...,...,...,...,...,...
145965,riptide-wcvii,Judges decision wins,2021,0.0,Opponent_match_history,NaN
145966,riptide-wcvii,Judges decision wins,2021,0.0,Opponent_match_history,NaN
145967,riptide-wcvii,Judges decision wins,2021,0.0,Opponent_match_history,NaN
145968,riptide-wcvii,Judges decision wins,2021,0.0,Opponent_match_history,NaN
145969,riptide-wcvii,Judges decision wins,2021,0.0,Opponent_match_history,NaN

In [48]:
joined_df['Value'] = joined_df['Value_x'].fillna(joined_df['Value_y'])

In [50]:
joined_df['Stats'] = joined_df['Stats_x'].fillna(joined_df['Stats_y'])

In [51]:
joined_df

,RobotName,Stats_x,Year,Value_x,Stats_y,Value_y,Value,Stats
0,tombstone-2021,Total matches,Career,35.0,NaN,NaN,35.0,Total matches
1,tombstone-2021,Win percentage,Career,71.0,NaN,NaN,71.0,Win percentage
2,tombstone-2021,Total wins,Career,25.0,NaN,NaN,25.0,Total wins
3,tombstone-2021,Losses,Career,10.0,NaN,NaN,10.0,Losses
4,tombstone-2021,Knockouts,Career,20.0,NaN,NaN,20.0,Knockouts
...,...,...,...,...,...,...,...,...
145965,riptide-wcvii,Judges decision wins,2021,0.0,Opponent_match_history,NaN,0.0,Judges decision wins
145966,riptide-wcvii,Judges decision wins,2021,0.0,Opponent_match_history,NaN,0.0,Judges decision wins
145967,riptide-wcvii,Judges decision wins,2021,0.0,Opponent_match_history,NaN,0.0,Judges decision wins
145968,riptide-wcvii,Judges decision wins,2021,0.0,Opponent_match_history,NaN,0.0,Judges decision wins
145969,riptide-wcvii,Judges decision wins,2021,0.0,Opponent_match_history,NaN,0.0,Judges decision wins

In [52]:
joined_df.drop(['Value_x', 'Value_y'], axis=1, inplace=True)

In [53]:
joined_df.drop(['Stats_x', 'Stats_y'], axis=1, inplace=True)

In [54]:
joined_df

             RobotName    Year  Value                 Stats
0       tombstone-2021  Career   35.0         Total matches
1       tombstone-2021  Career   71.0        Win percentage
2       tombstone-2021  Career   25.0            Total wins
3       tombstone-2021  Career   10.0                Losses
4       tombstone-2021  Career   20.0             Knockouts
...                ...     ...    ...                   ...
145965   riptide-wcvii    2021    0.0  Judges decision wins
145966   riptide-wcvii    2021    0.0  Judges decision wins
145967   riptide-wcvii    2021    0.0  Judges decision wins
145968   riptide-wcvii    2021    0.0  Judges decision wins
145969   riptide-wcvii    2021    0.0  Judges decision wins

[145970 rows x 4 columns]